apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: customers

bases:
  - ../base

resources:
  - configmap.yaml
  - secret.yaml

images:
  - name: ghcr.io/stack-food/stackfood-api-customers
    newTag: latest

replicas:
  - name: stackfood-customers
    count: 2
