apiVersion: v1
kind: Secret
metadata:
  name: stackfood-customers-secrets
  labels:
    app.kubernetes.io/name: stackfood-customers
    app.kubernetes.io/part-of: stackfood
type: Opaque
stringData:
  # Database Password
  POSTGRES_PASSWORD: "postgres"

  # AWS Credentials (if not using IRSA)
  AWS_ACCESS_KEY_ID: "ASIA6GBMFNFBD6VGEC4Q"
  AWS_SECRET_ACCESS_KEY: "DmD0Lz4crCqZtsWXwBgnIocaLzqI0x+PvrQT+Hpq"
