apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stackfood-customers-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /customers(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: stackfood-customers
            port:
              number: 8084
